stages:
  - release

before_script:
  - npm i -D @semantic-release/gitlab @semantic-release/changelog @semantic-release/git conventional-changelog-conventionalcommits

publish:
  only:
    refs:
      - master
  image: node:12
  stage: release
  script:
    - npx semantic-release
